on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm ci
      - run: npm run build
      - name: Add coverage to pull request
        uses: ArtiomTr/jest-coverage-report-action@v2
